### ISSUE TITLE
Extend document object

### ISSUE THREAD

**Issue by laszlo-karpati** [massiveart/MassiveSearchBundle#82]
Hi!

I am trying to add a new field to the Document object by a custom factory: 

My factory class:

```
namespace SearchBundle;

use Massive\Bundle\SearchBundle\Search\Factory as BaseFactory;

class Factory extends BaseFactory
{

    public function createDocument()
    {
        $document = new SearchBundle\Document();
        return $document;
    }

}
```

My Document class:

```
namespace SearchBundle;

use Massive\Bundle\SearchBundle\Search\Document as BaseDocument;

class Document extends BaseDocument {

    protected $editUrl;

    public function getEditUrl()
    {
        return $this->editUrl;
    }

    public function setEditUrl($editUrl)
    {
        $this->editUrl = $editUrl;
    }

    public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'description' => $this->description,
            'class' => $this->class,
            'url' => $this->url,
            'image_url' => $this->imageUrl,
            'locale' => $this->locale,
            'edit_url' => $this->editUrl,
        ];
    }
```

My config:

```
massive_search:
    persistence:
        doctrine_orm:
            enabled: true
    adapter: elastic
    metadata:
        prefix: %database_name%
    services:
        factory: factory_service

services:
    factory_service:
        class: SearchBundle\Factory
```

In the onPreIndex event I call this 
```
$document->setEditUrl('test-edit-url')
```

But as I see the index still does not include the edit_url field.

Did i miss something?

Thanks!
